FROM apache/airflow:2.9.0-python3.10

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-standard \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.10.txt"
