FROM apache/airflow:2.9.0-python3.10

USER airflow

ENV PATH="${PATH}:/home/airflow/.local/bin"

RUN pip install --no-cache-dir \
    snowflake-connector-python\
    apache-airflow-providers-standard \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.10.txt"


RUN pip install --no-cache-dir \
    dbt-core \
    dbt-snowflake